version: '3.9'
  services:
    node:
    image: ma_super_app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://user:[email protected]:5432/ma_super_app
    links:
      - db
    depends_on:
      - db

    mysql:
      image: mysql:7
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_USER=user
        - POSTGRES_PASSWORD=password
        - POSTGRES_DB=ma_super_app
