version: '3.3'
services:
  node:
    image: ma_super_app:1.0.0
    ports:
      - "3000:3000"
    links:
      - db
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: ma_super_app
      MYSQL_ROOT_PASSWORD: root
